name = "idchain"
defaultTargets = ["Idchain", "idchain", "tests"]

[[lean_lib]]
name = "Idchain"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "idchain"
root = "Main"

[[lean_exe]]
name = "tests"
root = "TestMain"
